[workspace]
members = [
    "programs/later/escrow",
    "programs/active/nv-usdc-vault",
    "programs/active/staking-manager",
    "programs/active/yield-distributor",
    "programs/active/position-tracker",
    "programs/active/noviscia-clearing",
    "programs/active/netting-engine",
    "programs/active/liquidation-vault",
    "programs/active/clearing-registry",
    "programs/active/token-nvsc",
    "programs/active/yield-router",
    "programs/active/jit-risk",
    "programs/active/sovereign-netting",
    "programs/active/ve-nvs",
    "programs/active/gateway-auction",
    "programs/active/noviscia-credit-line",
    "programs/later/burn-engine",
    "programs/later/spot-dex",
    "programs/later/bug-bounty",
    "programs/later/protocol-lp-vault",
    "sdk/rust/noviscia-credit-line",
    "vendor/wormhole-core-bridge-solana",
    "vendor/pyth-solano-receiver",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
solana-program = "2"
spl-token = "7"

[profile.release]
overflow-checks = true
lto = true
opt-level = 's'
strip = true
codegen-units = 1
panic = 'abort'