[workspace]
members = [
    "programs/escrow",
    "programs/lending-integrator",
    "programs/nv-usdc-vault",
    "programs/staking-manager",
    "programs/burn-engine",
    "programs/token-nvsc",
    "programs/yield-distributor",
    "programs/liquidation-vault",
    "programs/position-tracker",
    "programs/prediction_market",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
solana-program = "2"
spl-token = "7"

[profile.release]
overflow-checks = true