/**
 * @noviscia/sdk — Universal Noviscia Developer SDK.
 *
 * Single entry point exposing:
 *   - ids:         every program id + mint, env-overridable
 *   - addresses:   PDA derivation for position-tracker, netting-engine,
 *                  yield-router, nv-usdc-vault, burn/staking fee routing
 *   - NovisciaClient: anchor program wrappers over the whole stack
 *   - CollateralGateway: the Unified Collateral Gateway (deposit / withdraw /
 *                  open / liquidate / recall) — intent → instructions
 *   - translate / digest: payload translators (execution, clearing, netting
 *                  report, liquidation, recall)
 *   - sandbox:     simulate-first dry-runs, account-existence pre-checks,
 *                  JIT price fetching
 *   - economics / velocity / spreadsheet: the quantified TVV risk-pack engine
 *   - assumptions: the labeled single-source-of-truth assumption registry
 *   - waterfall:   the executable L1→L5 loss-waterfall + the 11 investor
 *                  failure scenarios (simulated, reproducible)
 */
export * from './ids';
export * from './addresses';
export { NovisciaClient, loadCliWallet, type NovisciaClientOptions } from './client';
export { CollateralGateway, type Side, type CollateralIntent } from './collateral';
export {
  translate, translateExecutionOrder, translateClearingOrder, translateNettingReport,
  translateRecall, translateLiquidation, digest,
  type TranslationKind, type TranslationRequest, type TranslationResult,
} from './payloads';
export {
  simulate, assertAccountsExist, toAccountMetas, fetchJitPrice,
  SandboxSimulator,
  type SimulationReport, type SimulatedPosition, type SimulatedMarketData, type MarginCheckResult,
} from './sandbox';
export {
  TenantOnboarding,
  CLEARING_REGISTRY_PROGRAM_ID as REGISTRY_PROGRAM_ID,
  type TenantRegistrationParams,
  type ExistingTenantParams,
  type NewTenantParams,
  type TenantAccounts,
} from './tenantOnboarding';
export {
  JitRiskClient,
  JIT_RISK_PROGRAM_ID,
} from './jitRisk';
export {
  CreditLineClient,
  CREDIT_LINE_PROGRAM_ID,
  LP_NAV_SPLIT_BPS,
  TREASURY_SPLIT_BPS,
  getBorrowerUsdc,
  type CreditLineState,
  type BorrowerState,
} from './creditLine';
export {
  ASSET_ENGINE_PROGRAM_ID,
  registryPDA,
  assetPoolPDA,
  assetVaultPDA,
  assetFeeVaultPDA,
  assetAuthorityPDA,
  creditLinePDA,
  deskPositionPDA,
  assetLpMintPDA,
  assetLpPositionPDA,
  anchorDiscriminator,
  buildInitializeIx,
  buildRegisterAssetIx,
  buildUpdateAssetParamsIx,
  buildSetAssetSupportIx,
  buildInitializeCreditLineIx,
  buildUpdateCreditLimitIx,
  buildSetCreditFrozenIx,
  buildSetPausedIx,
  buildAllocateAssetCapacityIx,
  buildRecreditAssetCapacityIx,
  buildSetKycRootIx,
  buildSettleDailyIx,
  buildDepositAssetLiquidityIx,
  buildWithdrawAssetLiquidityIx,
  buildWithdrawAssetFeesIx,
  registerAssetDefault,
  computePremium,
  computeLateFee,
  windowPosture,
  computeDepositShares,
  computeLpWithdrawValue,
  computeLpSharePrice,
  NVSC_PROFILE,
  USDC_PROFILE,
  WSOL_PROFILE,
  WINDOW_SLOTS,
  GRACE_SLOTS,
  LATE_FEE_BASE,
  LATE_FEE_RATE_BPS,
  type AssetParams,
  type AssetEngineRegistry,
  type InstitutionalCreditLine,
  type DeskPosition,
  type AssetPool,
  type WindowPosture,
} from './assetEngine';
export {
  JitoBundleClient,
  JitoRpcError,
  assembleVersionedTransactions,
  buildTipInstruction,
  selectTipAccount,
  resolveBundleTipLamports,
  JITO_BLOCK_ENGINE_URLS,
  KNOWN_JITO_TIP_ACCOUNTS,
  BUNDLE_MAX_TRANSACTIONS,
  DEFAULT_TIP_LAMPORTS,
  type BundleTipLimits,
  type JitoBundleStatus,
  type AssembleBundleOptions,
} from './jito';
export {
  leaderIsJito,
  guardNonJitoLeaderSlot,
  assertJitoLeader,
  NonJitoLeaderError,
  type LeaderEligibility,
} from './ability';
export {
  referenceTvvParams,
  defaultTvvParams,
  seniorTrancheUsdCents,
  juniorTrancheUsdCents,
  totalSlotsPerYear,
  eligibleSlots,
  systemicCapUsdCents,
  deskCapUsdCents,
  activeUtilizationUsdCents,
  slotFeeMicroUsd,
  grossRevenueUsdCents,
  netRevenueUsdCents,
  difAllocationUsdCents,
  totalLpYieldUsdCents,
  seniorYieldUsdCents,
  juniorYieldUsdCents,
  circuitBreakerDrainUsdCents,
  juniorDrainRatioBps,
  hardLockTriggered,
  ECONOMICS_BPS,
  MICRO_DOLLARS_PER_CENT,
  SLOT_SECONDS_NUM,
  SLOT_SECONDS_DEN,
  SECONDS_PER_YEAR,
  type TvvParams,
} from './economics';
export {
  FIXED_1E18,
  SLOTS_PER_SECOND_NUM,
  SLOTS_PER_SECOND_DEN,
  SLOTS_PER_DAY,
  COMPOUNDING_PERIODS_PER_YEAR,
  capitalTurnoverPerYear,
  slotPremiumScalingFactor,
  perTurnPremiumMicroUsd,
  aggregatedPremiumBps,
  dailyTransactionalPowerUsdCents,
  dailyVolumeVelocityUsd,
  grossApyTenthsBps,
  grossApyTenthsBpsAtActiveVolume,
  perSlotRevenueUsdCents,
  formulaDReconciles,
  jitoGapBps,
  jitoTipSlippageUsdCents,
  compoundedApyTenthsBps,
} from './velocity';
export {
  ACCELERATION,
  REAL_SLOTS_PER_DAY,
  REAL_GRACE_SLOTS,
  WINDOW_SANDBOX_SLOTS,
  GRACE_SANDBOX_SLOTS,
  SANDBOX_CADENCE_MS,
  realToSandboxSlots,
  sandboxToRealSlots,
  postureAt,
  Posture as SandboxPosture,
  windowWallClockSeconds,
} from './sandboxClock';
export {
  describePosture,
  frozenDesks,
  anyFrozen,
  sandboxSlotsToWallMs,
  type FrozenDesk,
} from './sandboxAccelerator';
export {
  DEFAULT_INPUTS,
  inputsToParams,
  computeWorkbook,
  referenceWorkbook,
  stressTestSpreadsheet,
  buildWorkbookCsv,
  excelSlotsPerYear,
  excelEligibleSlots,
  excelActiveVolume,
  excelMicroPremium,
  excelGrossRevenue,
  excelNetRevenue,
  excelLpPayout,
  type SpreadsheetInputs,
  type Workbook,
  type StressResult,
} from './spreadsheet';
export {
  ASSUMPTIONS,
  REFERENCE_POOL_USD_CENTS,
  SENIOR_LP_BPS,
  JUNIOR_LP_BPS,
  SYSTEMIC_CAP_BPS,
  DESK_CAP_BPS,
  AVG_ACTIVE_UTILIZATION_BPS,
  JITO_LANDING_BPS,
  BASE_RATE_BPS,
  JITO_TIP_BPS,
  DIF_BPS,
  INFRA_USD_CENTS,
  SENIOR_HURDLE_BPS,
  CIRCUIT_BREAKER_DRAIN_BPS,
  LOC_HAIRCUT_BPS,
  LOC_COVERAGE_BPS,
  DESK_COLLATERAL_COVERAGE_BPS,
  REFERENCE_RESERVE_USD_CENTS,
  DEBT_WINDOW_HOURS,
  GRACE_PERIOD_HOURS,
  assumptionByKey,
  isMeasured,
  type Provenance,
  type Assumption,
} from './assumptions';
export {
  subFloor,
  locEffectiveUsdCents,
  referenceJuniorUsdCents,
  referenceWaterfallState,
  absorbDefault,
  runDefaultCascade,
  singleDefaultScenario,
  correlatedDefaultsScenario,
  reserveShortfallScenario,
  locFailureScenario,
  liquidityShockScenario,
  nonJitoSlotsScenario,
  congestionScenario,
  staleDataScenario,
  duplicateRequestScenario,
  delayedSettlementScenario,
  infrastructureOutageScenario,
  allInvestorScenarios,
  type LocOutcome,
  type DeskDefaultEvent,
  type WaterfallState,
  type WaterfallResult,
  type Scenario,
} from './waterfall';
