/**
 * Reproducible investor stress-table generator.
 *
 * Runs the 11 checklist failure scenarios (sdk/src/waterfall.ts) plus the $
 * assumption registry (sdk/src/assumptions.ts) and emits two artifacts:
 *
 *   scripts/financial-model/investor-stress-tables.md — human-readable tables
 *   scripts/financial-model/investor-stress-tables.json — machine-readable
 *
 * Usage:
 *   node --import tsx scripts/financial-model/generate-investor-report.ts
 *
 * The output is deterministic (integer bigint engine, no floats/no RNG), so
 * re-running regenerates byte-identical artifacts. Everything in the tables is
 * labelled SIMULATED unless the provenance column says otherwise — a stress
 * table is not live performance.
 */
import { writeFileSync } from 'node:fs';
import {
  allInvestorScenarios,
  runDefaultCascade,
} from '../../sdk/src/waterfall';
import { ASSUMPTIONS, type Assumption } from '../../sdk/src/assumptions';
import { grossRevenueUsdCents, referenceTvvParams } from '../../sdk/src/economics';

const MAX_SCENARIO_NAME = 42;

const usd = (cents: bigint): string => {
  const dollars = Number(cents) / 100;
  return dollars.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
};

const pad = (s: string, n: number): string => s.padEnd(n);

function assumptionTable(): string {
  const out: string[] = [];
  out.push('## A · Assumption registry (single source of truth)');
  out.push('');
  out.push('| Assumption | Value (USD) | Provenance | Basis |');
  out.push('|---|---|---|---|');
  for (const a of ASSUMPTIONS) {
    const value = a.valueUsdCents === 0n ? '— (bps/flag)' : usd(a.valueUsdCents);
    out.push(`| ${a.label} | ${value} | \`${a.provenance}\` | ${a.basis} |`);
  }
  return out.join('\n');
}

function waterfallTable(): string {
  const out: string[] = [];
  out.push('## B · Loss-waterfall failure scenarios (all SIMULATED)');
  out.push('');
  out.push(
    `${pad('Scenario', MAX_SCENARIO_NAME)} | L1 desk | L2 LoC    | L3 reserves | L4 junior | L5 senior | uncovered | breaker`,
  );
  out.push(`${'-'.repeat(MAX_SCENARIO_NAME)}|---|---|---|---|---|---|---|`);
  for (const s of allInvestorScenarios()) {
    const { combined } = runDefaultCascade(s.state, s.events);
    const a = combined.absorbed;
    const row = [
      pad(s.name.slice(0, MAX_SCENARIO_NAME), MAX_SCENARIO_NAME),
      usd(a.deskCollateralUsdCents),
      usd(a.locUsdCents),
      usd(a.protocolReservesUsdCents),
      usd(a.juniorTrancheUsdCents),
      usd(a.seniorTrancheUsdCents),
      usd(a.uncoveredUsdCents),
      combined.circuitBreakerTripped ? 'TRIPPED' : '—',
    ].join(' | ');
    out.push(`| ${row} |`);
    out.push(`| **Description:** ${s.description || '—'}`);
    if (s.measuredNote) {
      out.push(`| **Note:** ${s.measuredNote}`);
    }
  }
  return out.join('\n');
}

function economicsRow(): string[] {
  const p = referenceTvvParams();
  return [
    'gross annualized revenue',
    usd(grossRevenueUsdCents(p)),
    `${Number(p.jitoLandingBps) / 100}% Jito eligibility (assumed)`,
  ];
}

function summary(): string {
  return [
    '## C · Reference sheet (module-1, $10M pool)',
    '',
    '| Metric | Value | Basis |',
    '|---|---|---|',
    `| ${economicsRow().join(' | ')} |`,
    '',
    '> The revenue line is SIMULATED on the audited integer model; the Jito',
    '> eligibility it depends on is `pending` live measurement.',
  ].join('\n');
}

function main(): void {
  const md = [
    '# Noviscia investor v0 — stress tables (reproducible)',
    '',
    `Generated by \`scripts/financial-model/generate-investor-report.ts\`. Deterministic — re-run regenerates identical output.`,
    '',
    '## Provenance rule',
    '',
    '`assumed` = design/planning input; `simulated` = deterministic engine output;',
    '`testnet-measured` / `production-measured` = observed on ledger (none in this file yet);',
    '`pending` = target for live measurement. **A simulated result is not live performance.**',
    '',
    assumptionTable(),
    '',
    waterfallTable(),
    '',
    summary(),
    '',
  ].join('\n');

  const rows = allInvestorScenarios().map((s) => {
    const { combined } = runDefaultCascade(s.state, s.events);
    return {
      name: s.name,
      provenance: s.provenance,
      description: s.description,
      measuredNote: s.measuredNote ?? null,
      absorbedUsd: {
        deskCollateral: Number(combined.absorbed.deskCollateralUsdCents) / 100,
        loc: Number(combined.absorbed.locUsdCents) / 100,
        protocolReserves: Number(combined.absorbed.protocolReservesUsdCents) / 100,
        junior: Number(combined.absorbed.juniorTrancheUsdCents) / 100,
        senior: Number(combined.absorbed.seniorTrancheUsdCents) / 100,
        uncovered: Number(combined.absorbed.uncoveredUsdCents) / 100,
      },
      circuitBreakerTripped: combined.circuitBreakerTripped,
    };
  });

  const json = {
    generator: 'scripts/financial-model/generate-investor-report.ts',
    determinism: 'integer-bigint engine, no floats, no RNG',
    generatedAt: 'Deterministic — timestamp intentionally omitted',
    assumptions: ASSUMPTIONS.map((a: Assumption) => ({
      key: a.key,
      label: a.label,
      valueUsdCents: a.valueUsdCents.toString(),
      provenance: a.provenance,
    })),
    scenarios: rows,
  };

  writeFileSync(
    'scripts/financial-model/investor-stress-tables.md',
    md,
    'utf8',
  );
  writeFileSync(
    'scripts/financial-model/investor-stress-tables.json',
    JSON.stringify(json, null, 2),
    'utf8',
  );
  console.log('wrote scripts/financial-model/investor-stress-tables.md');
  console.log('wrote scripts/financial-model/investor-stress-tables.json');
}

main();